# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mae/workspace/graphics-projects/rasten

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mae/workspace/graphics-projects/rasten

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mae/workspace/graphics-projects/rasten/CMakeFiles /Users/mae/workspace/graphics-projects/rasten//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mae/workspace/graphics-projects/rasten/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rasten

# Build rule for target.
rasten: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rasten
.PHONY : rasten

# fast build rule for target.
rasten/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/build
.PHONY : rasten/fast

src/CPURender/Rasterizer.o: src/CPURender/Rasterizer.cpp.o
.PHONY : src/CPURender/Rasterizer.o

# target to build an object file
src/CPURender/Rasterizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/CPURender/Rasterizer.cpp.o
.PHONY : src/CPURender/Rasterizer.cpp.o

src/CPURender/Rasterizer.i: src/CPURender/Rasterizer.cpp.i
.PHONY : src/CPURender/Rasterizer.i

# target to preprocess a source file
src/CPURender/Rasterizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/CPURender/Rasterizer.cpp.i
.PHONY : src/CPURender/Rasterizer.cpp.i

src/CPURender/Rasterizer.s: src/CPURender/Rasterizer.cpp.s
.PHONY : src/CPURender/Rasterizer.s

# target to generate assembly for a file
src/CPURender/Rasterizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/CPURender/Rasterizer.cpp.s
.PHONY : src/CPURender/Rasterizer.cpp.s

src/CPURender/RasterizerGeometry.o: src/CPURender/RasterizerGeometry.cpp.o
.PHONY : src/CPURender/RasterizerGeometry.o

# target to build an object file
src/CPURender/RasterizerGeometry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/CPURender/RasterizerGeometry.cpp.o
.PHONY : src/CPURender/RasterizerGeometry.cpp.o

src/CPURender/RasterizerGeometry.i: src/CPURender/RasterizerGeometry.cpp.i
.PHONY : src/CPURender/RasterizerGeometry.i

# target to preprocess a source file
src/CPURender/RasterizerGeometry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/CPURender/RasterizerGeometry.cpp.i
.PHONY : src/CPURender/RasterizerGeometry.cpp.i

src/CPURender/RasterizerGeometry.s: src/CPURender/RasterizerGeometry.cpp.s
.PHONY : src/CPURender/RasterizerGeometry.s

# target to generate assembly for a file
src/CPURender/RasterizerGeometry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/CPURender/RasterizerGeometry.cpp.s
.PHONY : src/CPURender/RasterizerGeometry.cpp.s

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Mesh.o: src/Mesh.cpp.o
.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/Model.o: src/Model.cpp.o
.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i
.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s
.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/ModelLoader.o: src/ModelLoader.cpp.o
.PHONY : src/ModelLoader.o

# target to build an object file
src/ModelLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/ModelLoader.cpp.o
.PHONY : src/ModelLoader.cpp.o

src/ModelLoader.i: src/ModelLoader.cpp.i
.PHONY : src/ModelLoader.i

# target to preprocess a source file
src/ModelLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/ModelLoader.cpp.i
.PHONY : src/ModelLoader.cpp.i

src/ModelLoader.s: src/ModelLoader.cpp.s
.PHONY : src/ModelLoader.s

# target to generate assembly for a file
src/ModelLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/ModelLoader.cpp.s
.PHONY : src/ModelLoader.cpp.s

src/ResourceManager.o: src/ResourceManager.cpp.o
.PHONY : src/ResourceManager.o

# target to build an object file
src/ResourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/ResourceManager.cpp.o
.PHONY : src/ResourceManager.cpp.o

src/ResourceManager.i: src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.i

# target to preprocess a source file
src/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.cpp.i

src/ResourceManager.s: src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.s

# target to generate assembly for a file
src/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rasten.dir/build.make CMakeFiles/rasten.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rasten"
	@echo "... src/CPURender/Rasterizer.o"
	@echo "... src/CPURender/Rasterizer.i"
	@echo "... src/CPURender/Rasterizer.s"
	@echo "... src/CPURender/RasterizerGeometry.o"
	@echo "... src/CPURender/RasterizerGeometry.i"
	@echo "... src/CPURender/RasterizerGeometry.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/ModelLoader.o"
	@echo "... src/ModelLoader.i"
	@echo "... src/ModelLoader.s"
	@echo "... src/ResourceManager.o"
	@echo "... src/ResourceManager.i"
	@echo "... src/ResourceManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

